/* Generated By:JavaCC: Do not edit this line. IMoParserConstants.java */
package jp.gr.java_conf.mizu.imo.parser;

public interface IMoParserConstants {

  int EOF = 0;
  int LINE_COMMENT = 6;
  int SHELL_COMMENT = 7;
  int K_AND = 8;
  int K_BOOLEAN = 9;
  int K_DEF = 10;
  int K_DO = 11;
  int K_ELSE = 12;
  int K_FALSE = 13;
  int K_IF = 14;
  int K_LET = 15;
  int K_IN = 16;
  int K_IO = 17;
  int K_INT = 18;
  int K_NOT = 19;
  int K_OR = 20;
  int K_RETURN = 21;
  int K_STRING = 22;
  int K_TRUE = 23;
  int K_UNIT = 24;
  int PLUS = 25;
  int MINUS = 26;
  int ASTER = 27;
  int SLASH = 28;
  int PERCENT = 29;
  int DOLLAR = 30;
  int LT = 31;
  int GT = 32;
  int LEQ = 33;
  int GEQ = 34;
  int RARROW = 35;
  int LARROW = 36;
  int BIND = 37;
  int CONCAT = 38;
  int ASSIGN = 39;
  int EQ = 40;
  int NOTEQ = 41;
  int PLUSPLUS = 42;
  int MINUSMINUS = 43;
  int COLON = 44;
  int SEMI = 45;
  int COLON2 = 46;
  int SHARP = 47;
  int DOT = 48;
  int LBRACE = 49;
  int RBRACE = 50;
  int LPAREN = 51;
  int RPAREN = 52;
  int COMMA = 53;
  int LBRACKET = 54;
  int RBRACKET = 55;
  int QUESTION = 56;
  int LAMBDA = 57;
  int INTEGER = 58;
  int DECIMAL_LITERAL = 59;
  int HEX_LITERAL = 60;
  int OCTAL_LITERAL = 61;
  int CHARACTER = 62;
  int STRING = 63;
  int ID = 64;
  int ERROR = 65;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<LINE_COMMENT>",
    "<SHELL_COMMENT>",
    "\"and\"",
    "\"bool\"",
    "\"def\"",
    "\"do\"",
    "\"else\"",
    "\"false\"",
    "\"if\"",
    "\"let\"",
    "\"in\"",
    "\"io\"",
    "\"int\"",
    "\"not\"",
    "\"or\"",
    "\"return\"",
    "\"string\"",
    "\"true\"",
    "\"unit\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"$\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"->\"",
    "\"<-\"",
    "\">>=\"",
    "\">>\"",
    "\"=\"",
    "\"==\"",
    "\"/=\"",
    "\"++\"",
    "\"--\"",
    "\":\"",
    "\";\"",
    "\"::\"",
    "\"#\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"?\"",
    "\"\\\\\"",
    "<INTEGER>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<CHARACTER>",
    "<STRING>",
    "<ID>",
    "<ERROR>",
  };

}
